version: '3.8'
services:
  nodeprueba:  
    build: .
    container_name: pruebita
    ports:
      - "5000:3000"
    volumes:
      - appdata:/app/data  # Monta un volumen para la persistencia de datos
    depends_on:
      - db

  db:
    image: mongo
    container_name: mymongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db  # Monta un volumen para la persistencia de datos de MongoDB

volumes:
  appdata:  # Volumen para los datos de la aplicación Node.js
  dbdata:   # Volumen para los datos de MongoDB
