version: '3.9'
services:
  nodePrueba:
    image: node
    container_name: pruebita
    ports:
      - "5000:3000"
    volumes:
      - mydata2:/app   # Monta el directorio actual en /app dentro del contenedor
    working_dir: /app   # Establece el directorio de trabajo como /app
    command: node app.js   # Ajusta el comando para ejecutar app.js

  db:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mymongo    
    ports:
      - "27017:27017"
